version: "3.9"

services:
  yauza_bot:
    build: .
    container_name: yauza_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - botnet

networks:
  botnet:
    driver: bridge
