version: "3.9"

services:
  yauza_bot:
    build: .
    container_name: yauza_bot
    restart: unless-stopped
    init: true
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - yauza_db:/app/data
    networks:
      - botnet
    environment:
      - DB_LITE=sqlite+aiosqlite:///data/bot.sqlite3

volumes:
  yauza_db:

networks:
  botnet:
    driver: bridge
